language: php

dist: focal

matrix:
    include:
        - php: 7.4
          env:
              - COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.4
        - php: 8.0
        - php: 8.1.0

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_script:
    - phpenv config-rm xdebug.ini
    - export PATH="$HOME/bin:$PATH"
    - ./install_composer.sh
    - composer validate
    - composer update $COMPOSER_FLAGS

script:
    - composer sniffer
    - composer stan
    - rm -rf /tests/Bundle/DataGridBundle/Fixtures/var/test
    - rm -rf /tests/Bundle/DataSourceBundle/Fixtures/var/test
    - composer unit
