---
version: '3'

services:
    web:
        image: fsiopenpl/docker-php-apache:alpine-8.1
        container_name: data-web
        ports:
            - 80:80
            - 443:443
        environment:
            PHP_IDE_CONFIG: 'serverName=localhost'
            XDEBUG_CONFIG: 'discover_client_host=false client_host=host.docker.internal'
            HOST_UID: 1000
            HOST_GID: 1000
            ELASTICSEARCH_URL: 'http://elasticsearch:9200'
        volumes:
            - .:/var/www/application
            - ~/.composer:/var/www/.composer
        extra_hosts:
            - "host.docker.internal:host-gateway"
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        container_name: data-elasticsearch
        environment:
            - cluster.name=data-elastica
            - xpack.security.enabled=false
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.1
        container_name: data-kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://data-elasticsearch:9200
            ELASTICSEARCH_HOSTS: '["http://data-elasticsearch:9200"]'
